#Django LogsInternal Server Error: /app/admin/logout/
Traceback (most recent call last):
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'localhost'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 402, in logout
    return LogoutView.as_view(**defaults)(request)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/contrib/auth/views.py", line 136, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/contrib/auth/views.py", line 141, in post
    redirect_to = self.get_success_url()
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/contrib/auth/views.py", line 41, in get_success_url
    return self.get_redirect_url() or self.get_default_redirect_url()
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/contrib/auth/views.py", line 152, in get_default_redirect_url
    return resolve_url(settings.LOGOUT_REDIRECT_URL)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/savelasquezo/imagine/core/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'localhost' is not a registered namespace
[35;1mHTTP POST /app/admin/logout/ 500 [0.12, 127.0.0.1:41930][0m
